name: tim_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  cloud_firestore: ^4.8.2
  country_code_picker: ^3.0.0
  country_state_city_picker: ^1.2.8
  fluttertoast: ^8.2.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  get_it: ^7.6.0
  intl: ^0.18.1
  intl_phone_field: ^3.2.0
  responsive_builder: ^0.7.0
  go_router: ^9.0.3
  flutter_typeahead: ^4.6.2
  video_player: ^2.7.0
  flutter_inset_box_shadow: ^1.0.8
  dropdown_button2: ^2.3.4
  multi_select_flutter: ^4.1.3
  provider: ^6.0.1
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Researcher
      fonts:
        - asset: fonts/researcher-researcher-bold-700.ttf
          weight: 700

    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf
